# -*- coding: utf-8 -*-
"""08_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtixhj3NuTCnn99h2wjMbbTJu9mhppbG
"""



"""<a href="https://colab.research.google.com/github/data602sps/assignments/blob/master/05_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 8**

# **Weeks 10 & 11- matplotlib & seaborn**
* In this homework assignment, you will explore and analyze a public dataset of your choosing. Since this assignment is “open-ended” in nature, you are free to expand upon the requirements below. However, you must meet the minimum requirments as indicated in each section.


* The preferred method for this analysis is in a .ipynb file. Feel free to use whichever platform of your choosing.  


### **Some data examples:**
•	https://www.data.gov/

•	https://opendata.cityofnewyork.us/

•	https://datasetsearch.research.google.com/

•	https://archive.ics.uci.edu/ml/index.php

### **Resources:**

•	https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

•	https://www.oreilly.com/library/view/python-data-science/9781491912126/ch04.html

•	https://www.data-to-viz.com/



### **Headings or comments**
**You are required to make use of comments, or headings for each section.  You must explain what your code is doing, and the results of running your code.**  Act as if you were giving this assignment to your manager - you must include clear and descriptive information for each section.

### **You may work as a group or indivdually on this assignment.**

# Introduction

In this section, please describe the dataset you are using.  Include a link to the source of this data.  You should also provide some explanation on why you choose this dataset.

The dataset contains the leading causes of death in the united states and in regions of the unitied states over time.  Despite the morbid topic, I thought it may be interesting to see how causes of death have shifted over time.  It may make for a comphrensive visual.  

https://catalog.data.gov/dataset/nchs-leading-causes-of-death-united-states

______________
# Data Exploration
Import your dataset into your .ipynb, create dataframes, and explore your data.  

Include:

* Summary statistics means, medians, quartiles,
* Missing value information
* Any other relevant information about the dataset.
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

us_deaths_csv = "https://github.com/division-zero/Data-602assignments/raw/refs/heads/main/NCHS_-_Leading_Causes_of_Death__United_States.csv"
#US causes of death imported
us_death_df = pd.read_csv(us_deaths_csv)
#view data
us_death_df.head()
us_death_df.describe()
print(us_death_df.isna().sum())

"""# Data Wrangling

Perform data wrangling.  You are free to use your best judgment here.  If you are stuck, look at previous assignment.
"""

#data looks relatively tidy. there are no NaN in this dataset
us_only_df=us_death_df[us_death_df['State']=='United States']#focusing on the US first
us_only_df.columns
us_simple_df=us_only_df[['Year','State', 'Cause Name','Deaths']] #removing the cause code and age adjusted death rate
us_simple_df.head()

"""# Visualizations

The main purpose of this assignment is to practice creating various visualizations using the matplotlib and seaborn library.

### **Part 1:**
Using matplotlib, create ***two or more plots*** that incorporate at least **5** of the following properties:

Note: these properties vary based on your data.  The goal is to practice creating visualizations and modifying its properties.

*   Use and change a legend position
*   Change a legend font size
*   Place a legend outside of the plot
*   Create a single legend for all subplots
*   Change the title and x/y labels
*   Change the marker, line colors, and line width
*   Add annotations
*   Modify Axis Text Ticks/Labels
*   Change size of axis Labels
*   Your own choice not included above


Plots that you can create **include**:

*   Scatter Plot
*   Bar plot
*   Line Chart
*   Multi Plots (e.g. using .subplot()
*   Histogram

You can add another plot not listed here if it works better for your data.  This is not a complete list of plots to create.

### **Part 2:**

Recreate the visualizations above using the Seaborn library as best as possible.  


**You are required to explain what each of your plots is representing. Plots without comments will not be accepted.**  In addition, please explain the properties you are showcasing.


### **Part 3:**
In a comment or text box, explain the differences between creating a plot in matplotlib and seaborn, based on your above plots.


"""

us_cause_year_df = us_simple_df

# Plotting each cause of death over time except the total

for cause in us_cause_year_df['Cause Name'].unique():
  if cause != 'All causes': #do not plot the total deaths
    cause_data = us_cause_year_df[us_cause_year_df['Cause Name'] == cause]
    plt.plot(cause_data['Year'], cause_data['Deaths'], label=cause)

# Adding labels, title, and legend
plt.xlabel('Year')
plt.ylabel('Deaths')
plt.title('Causes of Death Over Time in the United States')
plt.legend(loc='upper right', bbox_to_anchor=(1.3, 1))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()



"""# Conclusions  

After exploring your dataset, provide a short summary of what you noticed from this dataset.  
"""

